St aleksandra hodjuka lesson 3
antdolg1/jg_java_1_thursday_february_2024 pull request #12
Opened 2024-02-27 14:27 UTC by Aleksandra-Hodjuka

homework_lesson_3_level_4

2024-03-03 10:15 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/lesson_3/level_3/Book.java
Хммм, класс выглядит довольно нестандартно. Тут два больших пункта, которые нужно исправить:

1. Классы в конструкторе: Определять классы Chapter1 и Chapter2 прямо в конструкторе - это нестандартно. Обычно так не делают, потому что это создает лишние сложности и ограничивает использование этих классов только внутри конструктора Book.

2. Дублирование данных: У тебя в классе и во вложенных классах повторяются поля chapter1, chapter2, text1, text2. Это может запутать и усложнить поддержку кода, лучше избегать такого дублирования.

Короче говоря, структура класса выглядит усложненной и не очень практичной. Тут надо будет переделать.

Создай отдельно класс Book и отдельно класс Chapter. В каждом добавь соответствующие конструкторы и getters/setters по необходимости. Нет смысла создавать класс Chapter1 и Chapter2, так как это дублирование.

2024-03-03 10:15 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/lesson_3/level_4/DoctorTimetable.java
Тут тоже самое что и в классе Book.

2024-03-03 10:16 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/lesson_3/level_4/DoctorTimetableApp.java
> +import java.sql.SQLOutput;
Лишний импорт, удали его пожалуйста.

2024-03-03 10:17 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/lesson_4/level_1/Task2.java
> +
Не нужно оставлять столько пустых строк. Пожалуйста удали лишние пустые строки тут и в других классах.

2024-03-03 10:21 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/lesson_4/level_3/Task10.java
> +        else if (C > A && C > B) System.out.println(C);
Если ты начала писать тело if внутри фигурных скобочек, то сохраняй этот стиль для всего выражения. Мешать стили, когда ты одну часть пишешь с {}, другую без - это плохая практика.

2024-03-03 10:22 UTC, antdolg1 requested changes
В целом неплохо, но требуются некоторые правки. Посмотри мои комментарии. Если будут вопросы - смело пиши.

2024-03-04 14:12 UTC, Aleksandra-Hodjuka commented
Привет, попыталась все исправить. Как получилось?

2024-03-04 18:33 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/lesson_3/level_3/BookApp.java
> +        Chapter Chapter1 = new Chapter("Chapter 1", "Main idea of the book.");
Не забывай что в названиях переменных мы используем camelCase. Переменные с большой буквы не называем. Исправь пожалуйста.

2024-03-04 18:34 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/lesson_3/level_4/DoctorTimetableApp.java
> +        DoctorTimetable DoctorTimeTable1 = new DoctorTimetable("James Scott", "Surgeon",
В этом классе тоже исправь названия переменных.

2024-03-04 18:41 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/lesson_3/level_3/Chapter.java
> +    String Text;
Тут тоже нужно поменять название переменной.

2024-03-04 18:41 UTC, antdolg1 requested changes
Вижу что многие моменты ты исправила. Это отлично. Осталось ещё пару ошибочек.

2024-03-05 07:02 UTC, Aleksandra-Hodjuka commented
Посмотри, пожалуйста, еще раз. Что-то я туплю неимоверно. Мне свойственно усложнять вещи там, где это не нужно.

2024-03-17 17:48 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/lesson_3/level_3/Book.java
> +        this.yearOfPrint = yearOfPrint;
Параметр chapter должен быть не типа String, а типа Chapter. То есть ты создаешь объект Chapter и кладешь его в Book.

2024-03-17 17:49 UTC, antdolg1 requested changes
Осталось добить класс Book, поместив объект Chapter в конструктор Book как один из параметров.

2024-03-18 09:08 UTC, Aleksandra-Hodjuka commented
Исправила Book.

2024-03-22 09:01 UTC, closed without merging