St karina cmile lesson5
antdolg1/jg_java_1_thursday_february_2024 pull request #22
Opened 2024-03-06 21:28 UTC by KarinaSoha

2024-03-17 18:02 UTC, antdolg1 commented on src/main/java/students/karina_cmile/lesson_5/level_2_intern/Task_11.java
> +        int number3;
Эти две переменные можно смело удалять, так как мы их нигде не используем.

2024-03-17 18:03 UTC, antdolg1 commented on src/main/java/students/karina_cmile/lesson_5/level_2_intern/Task_12.java
> +        int number3;
Эти две переменные можно смело удалять, так как мы их нигде не используем.

2024-03-17 18:26 UTC, antdolg1 commented on src/main/java/students/karina_cmile/lesson_5/level_2_intern/Task_14.java
> +        double average = sum / 3;
Тут более правильно будет делить не на захардкоженную длинну массива, а на numbers.length.

2024-03-17 18:27 UTC, antdolg1 requested changes
Есть пару небольших моментов, исправь их пожалуйста и всё будет в порядке.

2024-03-17 20:19 UTC, KarinaSoha commented
Спасибо, исправила.

2024-03-18 08:13 UTC, antdolg1 approved these changes

2024-03-18 08:14 UTC, merged