St aleksandra hodjuka lesson 6 level 3
antdolg1/jg_java_1_thursday_february_2024 pull request #25
Opened 2024-03-12 14:22 UTC by Aleksandra-Hodjuka

2024-03-31 09:13 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/level_2/DayOfTheWeekDetectorDemo.java
> +
Старайся не оставлять ненужных пустых строк в конце классов и не забывай делать автоформатирование.

2024-03-31 09:30 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/level_1/NumberUtils.java
> +}
Это задание выполнено не до конца правильно. Ты упростила метод и написала его в одну строку. Тут всё отлично. Теперь давай разберёмся с тестами. Мне очень нравятся твои названия тестов, тут ты проделала хорошую работу. Осталось доработать само содержание тестов. 
Во-первых в методах assertTrue & assertFalse нет никакого смысла, так как они сейчас ничего не делают, в них нет внутренней логики. Так что эти методы мы можем убрать.
Далее нам нужно написать сами тесты. Один из вариантов как мы можем это сделать - в каждом методе создаешь переменную realResult и переменную expectedResult. Где expectedResult это ожидаемый результат, который ты знаешь заранее, а realResult это результат, который даст твой метод NumberUtils.isEven. Далее ты сравниваешь эти результаты и результат этого сравнения возвращаешь.

Вот небольшой пример как это можно сделать:
```
  public static void testIsEvenWithOddNumber() {
        int number = 7;
        boolean expected = false;
        boolean result = isEven(number);
        printTestResult("Positive Odd Number", expected, result);
    }
```

И вспомогательный метод для вывода результатов:

```
    private static void printTestResult(String testName, boolean expected, boolean result) {
        if (expected == result) {
            System.out.println(testName + ": Test passed");
        } else {
            System.out.println(testName + ": Test failed (Expected " + expected + " but got " + result + ")");
        }
    }
```

2024-03-31 09:32 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/level_3/ArrayServiceTest.java
> +
У тебя тут похожая история, как и в NumberUtils. Пожалуйста убери assertTrue, который ничего не делает и внеси небольшие правки. Как пример смотри мой комментарий к  классу NumberUtils.

2024-03-31 09:33 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/level_3/ArrayService.java
> +
Убери лишние пустые строки, они тут не нужны.

2024-03-31 09:33 UTC, antdolg1 requested changes
Требуются некоторые исправления, посмотри мои комментарии.

2024-04-09 13:00 UTC, Aleksandra-Hodjuka commented
Привет. Сделала исправления. Проверь, пожалуйста.

2024-04-18 13:43 UTC, antdolg1 approved these changes

2024-04-18 13:43 UTC, merged