St Kristina Manevica homework Lesson 5
antdolg1/jg_java_1_thursday_february_2024 pull request #26
Opened 2024-03-12 15:22 UTC by KristinaManevica

2024-03-17 19:04 UTC, antdolg1 commented on src/main/java/students/kristina_manevica/lesson_5/homework/level_4/ArrayUtilTest.java
> +    }
Это не совсем тест. В тесте ты должна проверить что твой метод реально находит самое большое число. То есть ты создаешь тестовый массив со значениями которые ты знаешь и соответственно ты знаешь какое значение самое большое. Потом ты запускаешь свой метод findMaxNumber на этом массиве и сравниваешь результат метода, с реальным самым большим числом в массиве. Пожалуйста переделай этот тест и тест на самое маленькое значение.

2024-03-17 19:05 UTC, antdolg1 requested changes
Очень хорошая работа, но есть небольшие недочёты в тестах. Посмотри мой комментарий.

2024-04-05 18:27 UTC, KristinaManevica commented on src/main/java/students/kristina_manevica/lesson_5/homework/level_4/ArrayUtilTest.java
> +    }
Resolved

2024-04-18 13:44 UTC, antdolg1 approved these changes

2024-04-18 13:44 UTC, merged