St aleksandra hodjuka lesson 4 level 4
antdolg1/jg_java_1_thursday_february_2024 pull request #29
Opened 2024-03-14 14:28 UTC by Aleksandra-Hodjuka

2024-03-17 18:41 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/lesson_4/level_2/Task5.java
> +            System.out.println("Неверное число!!!");
Старайся не смешивать стили, если начала писать фигурные скобочки, то пиши их везде.

2024-03-17 18:42 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/lesson_4/level_3/Task8.java
> +        else if (A != B && B != C) {
Этот else if лишний, ты можешь добавить B != C как дополнительное условие в первый if.

2024-03-17 18:49 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/lesson_4/level_4/Calculator.java
> +    }
Честно говоря в этом методе нет смысла, это дубликат метода sub1. Можешь смело его удалять.

2024-03-17 18:49 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/lesson_4/level_4/Calculator.java
> +    }
Тоже самое что и с sub2, смело удаляй этот метод.

2024-03-17 18:52 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/lesson_4/level_4/Calculator.java
> +        } else return secondNumber;
Добавь недостающие {} тут и во всех остальных местах где ты мешаешь стили.

2024-03-17 18:54 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/lesson_4/level_4/Calculator.java
> +        } else if (firstNumber > thirdNumber)
Тут у тебя неправильная логика. Если у тебя первое число больше второго, то ты сразу возвращаешь что первое число самое большое, даже не сравнив его с третьим числом. Чтобы убедиться что число самое большое, ты должна его сравнить со всеми числами. Мы делали такое на лекции, можешь подсмотреть в одной из папок lessoncode.

2024-03-17 18:54 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/lesson_4/level_4/Calculator.java
> +        if (firstNumber == (secondNumber = thirdNumber)) {
= это оператор присвоения, а == это сравнение. Исправь пожалуйста ошибку.

2024-03-17 18:55 UTC, antdolg1 requested changes
Требуются исправления, есть ошибки. Посмотри мои комментарии.

2024-03-18 08:12 UTC, Aleksandra-Hodjuka reviewed
Привет. Постаралась все исправить.

2024-03-18 08:12 UTC, Aleksandra-Hodjuka commented
Проверь теперь, пожалуйста.

2024-03-18 08:17 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/lesson_7/WorldService.java
Этот класс по идее не должен быть в ветке с домашками 4ого урока.

2024-03-18 08:18 UTC, antdolg1 approved these changes

2024-03-18 08:20 UTC, antdolg1 approved these changes

2024-03-18 08:20 UTC, antdolg1 requested changes
Убери домашку 7ого урока из этой ветки и все будет хорошо.

2024-03-18 08:28 UTC, Aleksandra-Hodjuka commented
Убрала.

2024-03-18 11:50 UTC, Aleksandra-Hodjuka commented on src/main/java/students/aleksandra_hodjuka/lesson_4/level_4/Calculator.java
> +    }
Антон , я удалила эти методы,но все-таки мне не понятно, почему они дубликаты. sub1 отнимает первое число от второго, а sub2 -второе от первого. Если предположить, что это два разных числа, то результаты этих двух вычислений тоже будут разные.

2024-03-18 11:51 UTC, Aleksandra-Hodjuka commented on src/main/java/students/aleksandra_hodjuka/lesson_4/level_4/Calculator.java
> +    }
Тоже самое относиться и к div1 -div2.

2024-03-24 20:38 UTC, antdolg1 approved these changes

2024-03-24 20:39 UTC, merged