St aleksandra hodjuka lesson 7
antdolg1/jg_java_1_thursday_february_2024 pull request #34
Opened 2024-03-20 14:39 UTC by Aleksandra-Hodjuka

2024-04-01 09:36 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/lesson_7/WordService.java
> +}
В текущем решении слова "Apple" и "apple" будут считаться разными словами.  Советую привести строку к нижнему регистру перед тем как с ней начинать работать.

2024-04-01 09:37 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/lesson_7/WordService.java
> +        Map<String, Integer> wordCount = new HashMap<>();
Молодец что используешь HashMap 👍   (хоть мы это ещё и не проходили)

2024-04-01 09:39 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/lesson_7/WordService.java
> +    public String findMostFrequentWord(String text) {
Этот метод можно смело делать статическим, чтобы не нужно было создавать экземпляр класса в дальнейшем, чтобы его вызвать.

2024-04-01 09:41 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/lesson_7/PowerCalculator.java
> +    int thePowerToRaise;
Эти две строки можно смело удалять, так как ты их пересоздаешь ниже и сразу заполняешь значениями.

2024-04-01 09:44 UTC, antdolg1 commented on src/main/java/students/aleksandra_hodjuka/lesson_7/PowerCalculator.java
> +}
В твоей реализации нет обработки случаев, когда степень отрицательная. Напоминаю, что возведение числа в отрицательную степень эквивалентно делению единицы на это число, возведенное в соответствующую положительную степень. Было бы хорошо добавить это в твою программу.

2024-04-01 09:45 UTC, antdolg1 requested changes
Очень неплохо. Есть пару недочётов. Посмотри мои комментарии.

2024-04-09 13:02 UTC, Aleksandra-Hodjuka commented
Тут тоже исправила.

2024-04-18 13:47 UTC, merged